version: "3"

services:
  backend:
    restart: always
    build: 
      context: .
      dockerfile: ./docker/local/express/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - ./backend:/app
      - /app/node_modules
      - .:/app
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
    networks:
      - mern-invoice_mernshop
    ports:
      - "1998:1998"
    command: npm run server
    


  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/local/Dockerfile
    restart: always
    volumes:
            - ./frontend:/app
            - /app/node_modules
    networks:
       - mern-invoice_mernshop
  
  mongodb:
      image: mongo
      restart: always
      container_name: mongo-db
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      volumes:
        - mongodb-data:/data/db
      networks:
        - mern-invoice_mernshop
        
  mongo-express:
    image: mongo-express:0.54.0
    depends_on:
         - mongodb
    ports:
        - "8081:8081"
    environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    networks:
        - mern-invoice_mernshop
    
  mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - mern-invoice_mernshop

  nginx:
    build:  
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - mern-invoice_mernshop

networks:
  mern-invoice_mernshop:
    driver: bridge

volumes:
  mongodb-data:
  static_volume:

